pipeline:
  name: sudartest
  identifier: sudartest
  projectIdentifier: TF_Test_Sudar
  orgIdentifier: default
  tags:
    name: mohit
    type: testing
  stages:
    - stage:
        name: approval
        identifier: approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approval step
                  identifier: approval_step
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.ProductManagement
                    approverInputs:
                      - name: testinput
                        defaultValue: ""
              - step:
                  type: ShellScript
                  name: sudarstep
                  identifier: sudarstep
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables:
                      - name: inputvar
                        type: String
                        value: test
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: child
        identifier: child
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Approval_Pipeline
          project: TF_Test_Sudar
          outputs: []
          inputSetReferences:
            - ""
            - ""
            - ""
        tags: {}
        variables:
          - name: test234
            type: String
            description: sdfs
            required: false
            value: <+input>.executionInput()
    - stage:
        name: deploystage
        identifier: deploystage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: <+input>
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: account.dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev
          services:
            values: <+input>
            metadata:
              parallel: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Retry
                spec:
                  retryCount: 4
                  retryIntervals:
                    - 1d
                  onRetryFailure:
                    action:
                      type: Ignore
        variables: []
    - stage:
        name: template
        identifier: template
        template:
          templateRef: approvaltemplate
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: httpstep
                      type: Http
                      spec:
                        inputVariables:
                          - name: testinput
                            type: String
                            value: <+input>
  variables:
    - name: input_set_name
      type: String
      description: Descriptive stuff
      required: true
      value: <+input>
    - name: input_set_name2
      type: String
      description: ""
      value: <+input>
    - name: input_set_name3
      type: String
      description: ""
      value: <+input>
    - name: required_variable
      type: String
      description: ""
      required: false
      value: "10"
  allowStageExecutions: false
  flowControl:
    barriers:
      - name: testbarrier
        identifier: testbarrier
