pipeline:
  name: sudartest
  identifier: sudartest
  projectIdentifier: TF_Test_Sudar
  orgIdentifier: default
  tags:
    run: testing
  stages:
    - stage:
        name: approval
        identifier: approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approval step
                  identifier: approval_step
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.ProductManagement
                    approverInputs: []
              - step:
                  type: ShellScript
                  name: sudarstep
                  identifier: sudarstep
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables:
                      - name: inputvar
                        type: String
                        value: test
                    outputVariables: []
                  timeout: 10m
        tags: {}
        when:
          pipelineStatus: Success
          condition: <+input>
    - stage:
        name: customstage
        identifier: customstage
        template:
          templateRef: approvaltemplate
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: httpstep
                      type: Http
                      spec:
                        inputVariables:
                          - name: testinput
                            type: String
                            value: <+input>
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
