pipeline:
  name: sudartest
  identifier: sudartest
  projectIdentifier: TF_Test_Sudar
  orgIdentifier: default
  tags:
    name: mohit
    type: prod
  stages:
    - stage:
        name: approval
        identifier: approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approval step
                  identifier: approval_step
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.ProductManagement
                    approverInputs:
                      - name: testinput
                        defaultValue: ""
        tags: {}
        when:
          pipelineStatus: Success
    - stage:
        name: child
        identifier: child
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Approval_Pipeline
          project: TF_Test_Sudar
          outputs: []
          inputs:
            identifier: Approval_Pipeline
            stages:
              - stage:
                  identifier: customs3
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            spec:
                              environmentVariables:
                                - name: input4
                                  type: String
                                  value: <+input>
                            timeout: <+input>
        tags: {}
        variables:
          - name: test234
            type: String
            description: sdfs
            required: false
            value: <+input>.executionInput()
    - stage:
        name: deploystage
        identifier: deploystage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo <+serviceVariables.ServiceVar>
                    environmentVariables:
                      - name: test
                        type: Number
                        value: <+input>
                    outputVariables: []
                    includeInfraSelectors: <+input>
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: test_envi
            deployToAll: false
            infrastructureDefinitions:
              - identifier: vl_infra_dummy
          service:
            serviceRef: SudarService
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Retry
                spec:
                  retryCount: 4
                  retryIntervals:
                    - 1d
                  onRetryFailure:
                    action:
                      type: Ignore
    - stage:
        name: Custom
        identifier: Custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.execution.stage.deploystage.pipeline.stages.deploystage.spec.serviceVariables>
                          exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: template
        identifier: template
        template:
          templateRef: approvaltemplate
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: httpstep
                      type: Http
                      spec:
                        inputVariables:
                          - name: testinput
                            type: String
                            value: <+input>
                  - step:
                      identifier: ShellScript_1
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
  variables:
    - name: input_set_name
      type: String
      description: Descriptive stuff
      required: true
      value: <+input>
    - name: input_set_name2
      type: String
      description: ""
      value: <+input>
    - name: input_set_name3
      type: String
      description: ""
      value: <+input>
    - name: required_variable
      type: String
      description: ""
      required: false
      value: "10"
  allowStageExecutions: true
  flowControl:
    barriers:
      - name: testbarrier
        identifier: testbarrier
